CREATE TABLE request_filter
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filter_name     VARCHAR(255)                            NOT NULL,
    filter_type     VARCHAR(255)                            NOT NULL,
    selected_filter VARCHAR(255)                            NOT NULL,
    select_key      VARCHAR(255)                            NOT NULL,
    select_value    VARCHAR(255)                            NOT NULL,
    route_id        BIGINT,
    CONSTRAINT pk_request_filter PRIMARY KEY (id)
);

CREATE TABLE request_predicate
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    predicate_name         VARCHAR(255)                            NOT NULL,
    predicate_key          VARCHAR(255)                            NOT NULL,
    predicate_value        VARCHAR(255)                            NOT NULL,
    request_predicate_type VARCHAR(255)                            NOT NULL,
    route_id               BIGINT,
    CONSTRAINT pk_request_predicate PRIMARY KEY (id)
);

CREATE TABLE route_dao
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_identifier   VARCHAR(255)                            NOT NULL,
    path               VARCHAR(255)                            NOT NULL,
    method             VARCHAR(255)                            NOT NULL,
    route_uri_blue     VARCHAR(255)                            NOT NULL,
    route_uri_green    VARCHAR(255),
    is_weight          BOOLEAN,
    green_weight       INTEGER,
    blue_weight        INTEGER,
    is_feature_flag    BOOLEAN,
    feature_flag_key   VARCHAR(255),
    feature_flag_value VARCHAR(255),
    CONSTRAINT pk_route_dao PRIMARY KEY (id)
);

ALTER TABLE request_filter
    ADD CONSTRAINT FK_REQUEST_FILTER_ON_ROUTE FOREIGN KEY (route_id) REFERENCES route_dao (id);

ALTER TABLE request_predicate
    ADD CONSTRAINT FK_REQUEST_PREDICATE_ON_ROUTE FOREIGN KEY (route_id) REFERENCES route_dao (id);